version: "3.8"
services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: APP
      APP_USER_PASSWORD: app_pwd
      ORACLE_DATABASE: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
    restart: unless-stopped

  api:
    build: .
    container_name: financeiro-api
    depends_on:
      - oracle-xe
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle-xe:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app_pwd
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.Oracle12cDialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      SPRINGDOC_API_DOCS_PATH: /v3/api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRINGDOC_SWAGGER_UI_DISPLAY_OPERATION_ID: "true"
      SPRINGDOC_SWAGGER_UI_DEFAULT_MODELS_EXPAND_DEPTH: "-1"
      SPRINGDOC_SWAGGER_UI_DISPLAY_REQUEST_DURATION: "true"
      SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER: alpha
      SPRINGDOC_SWAGGER_UI_TAGS_SORTER: alpha

    restart: unless-stopped
